routes:
# =========================
# Health Check Microservice
# =========================

  - regex: '^/health(/*[a-zA-Z0-9]*)?'
    inputModel: main.daos.Healthcheck
    outputModel: main.daos.Healthcheck
    controller: main.controllers.HealthcheckController

  - regex: '^/dbhealth(/*[a-zA-Z0-9]*)?'
    inputModel: main.daos.Healthcheck
    outputModel: main.daos.Healthcheck
    controller: main.controllers.DatabaseHealthcheckController
    
# =========================
# User Microservice
# =========================

  - regex: '^/user(/*[a-zA-Z0-9]*)?'
    inputModel: main.daos.UserAccount
    outputModel: main.daos.UserAccount
    controller: main.controllers.UserAccountController

# =========================
# User Account Microservice
# =========================

  - regex: '^/user_test(/*[a-zA-Z0-9]*)?'
    inputModel: main.daos.UserNamespace
    outputModel: main.daos.User
    controller: main.controllers.UserController

