routes:
# =========================
# Health Check Microservice
# =========================

  - regex: '^/health(/*[a-zA-Z0-9]*)?'
    inputModel: main.daos.Healthcheck
    outputModel: main.daos.Healthcheck
    controller: main.controllers.HealthcheckController
    shouldValidatePost: true
    shouldValidatePut: true
    shouldValidateGet: false

  - regex: '^/dbhealth(/*[a-zA-Z0-9]*)?'
    inputModel: main.daos.Healthcheck
    outputModel: main.daos.Healthcheck
    controller: main.controllers.DatabaseHealthcheckController
    shouldValidatePost: true
    shouldValidatePut: true
    shouldValidateGet: false
    
# =========================
# User Balances Microservice
# =========================

  - regex: '^/user/balances*'
    inputModel: main.daos.UserAccount
    outputModel: main.daos.ChallengeToUnsharedTransactionsList
    controller: main.controllers.UserAccountController
    shouldValidatePost: false
    shouldValidatePut: false
    shouldValidateGet: true

# =========================
# User Microservice
# =========================

  - regex: '^/user(/*[a-zA-Z0-9]*)?'
    inputModel: main.daos.UserAccount
    outputModel: main.daos.UserAccount
    controller: main.controllers.UserAccountController
    shouldValidatePost: false
    shouldValidatePut: true
    shouldValidateGet: true

# =========================
# Challenge Balances Microservice
# =========================

  - regex: '^/challenge/balances*'
    inputModel: main.daos.Challenge
    outputModel: main.daos.EmailToChallengeBalanceList
    controller: main.controllers.ChallengeController
    shouldValidatePost: false
    shouldValidatePut: false
    shouldValidateGet: true

# =========================
# Challenge Microservice
# =========================

  - regex: '^/challenge(/*[a-zA-Z0-9]*)?'
    inputModel: main.daos.Challenge
    outputModel: main.daos.Challenge
    controller: main.controllers.ChallengeController
    shouldValidatePost: true
    shouldValidatePut: true
    shouldValidateGet: true

# =========================
# Challenges Microservice
# =========================

  - regex: '^/challenges(/*[a-zA-Z0-9]*)?'
    inputModel: main.daos.Challenge
    outputModel: main.daos.Challenge
    controller: main.controllers.ChallengeController
    shouldValidatePost: true
    shouldValidatePut: true
    shouldValidateGet: true

# =========================
# Completion Criteria Microservice
# =========================

  - regex: '^/completion(/*[a-zA-Z0-9]*)?'
    inputModel: main.daos.CompletionCriteria
    outputModel: main.daos.CompletionCriteria
    controller: main.controllers.CompletionCriteriaController
    shouldValidatePost: true
    shouldValidatePut: true
    shouldValidateGet: true

# =========================
# Rewards Microservice
# =========================

  - regex: '^/reward(/*[a-zA-Z0-9]*)?'
    inputModel: main.daos.Reward
    outputModel: main.daos.Reward
    controller: main.controllers.RewardController
    shouldValidatePost: true
    shouldValidatePut: true
    shouldValidateGet: true

# =========================
# Token Microservice
# =========================

  - regex: '^/token(/*[a-zA-Z0-9]*)?'
    inputModel: main.daos.Token
    outputModel: main.daos.Token
    controller: main.controllers.TokenController
    shouldValidatePost: true
    shouldValidatePut: true
    shouldValidateGet: true

  - regex: '^/tokens(/*[a-zA-Z0-9]*)?'
    inputModel: main.daos.Token
    outputModel: main.daos.Token
    controller: main.controllers.TokensController
    shouldValidatePost: true
    shouldValidatePut: true
    shouldValidateGet: true

# =========================
# Transactions Microservice
# =========================

  - regex: '^/transaction(/*[a-zA-Z0-9]*)?'
    inputModel: main.daos.Transaction
    outputModel: main.daos.Transaction
    controller: main.controllers.TransactionController
    shouldValidatePost: true
    shouldValidatePut: true
    shouldValidateGet: true

# =========================
# User Account Microservice
# =========================

  - regex: '^/user_test(/*[a-zA-Z0-9]*)?'
    inputModel: main.daos.UserNamespace
    outputModel: main.daos.User
    controller: main.controllers.UserController
    shouldValidatePost: true
    shouldValidatePut: true
    shouldValidateGet: true

