version: 2.1

jobs:
  build:
    working_directory: ~/ncnt-api
    docker: # run the steps with Docker
    - image: circleci/openjdk:8-jdk-browsers
    steps:
    - checkout
    - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
        # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
        key: ncnt-api-{{ checksum "pom.xml" }}
    - run: mvn clean test # run the actual tests
    - save_cache: # saves the project dependencies
        paths:
        - ~/.m2
        key: ncnt-api-{{ checksum "pom.xml" }}