routes:
# =========================
# Health Check Microservice
# =========================

  - regex: '^/health(/*[a-zA-Z0-9]*)?'
    model: main.daos.Healthcheck
    controller: kotlinserverless.main.controllers.HealthcheckController
    
# =========================
# User Microservice
# =========================

  - regex: '^/user(/*[a-zA-Z0-9]*)?'
    model: main.daos.User
    controller: main.controllers.UserController

# =========================
# Challenges Microservice
# =========================

  - regex: '^/challenge(/*[a-zA-Z0-9]*)?'
    model: main.daos.Challenge
    controller: main.controllers.ChallengeController

  - regex: '^/challenges(/*[a-zA-Z0-9]*)?'
    model: main.daos.Challenge
    controller: main.challenges.controllers.ChallengesController

# =========================
# Completion Criteria Microservice
# =========================

  - regex: '^/completion(/*[a-zA-Z0-9]*)?'
    model: main.daos.CompletionCriteria
    controller: main.controllers.CompletionCriteriaController

# =========================
# Rewards Microservice
# =========================

  - regex: '^/reward(/*[a-zA-Z0-9]*)?'
    model: main.daos.Reward
    controller: main.controllers.RewardController

# =========================
# Token Microservice
# =========================

  - regex: '^/token(/*[a-zA-Z0-9]*)?'
    model: main.daos.Token
    controller: main.controllers.TokenController

  - regex: '^/tokens(/*[a-zA-Z0-9]*)?'
    model: main.daos.Token
    controller: main.tokens.controllers.TokensController

# =========================
# Transactions Microservice
# =========================

  - regex: '^/transaction(/*[a-zA-Z0-9]*)?'
    model: main.daos.Transaction
    controller: main.controllers.TransactionController

# =========================
# User Account Microservice
# =========================

  - regex: '^/user_account(/*[a-zA-Z0-9]*)?'
    model: main.daos.UserAccount
    controller: main.userAccounts.models.UserAccountController

