routes:
# =========================
# Health Check Microservice
# =========================

  - regex: '^/health(/*[a-zA-Z0-9]*)?'
    model: main.daos.Healthcheck
    controller: kotlinserverless.main.controllers.HealthcheckController
    
# =========================
# User Microservice
# =========================

  - regex: '^/user(/*[a-zA-Z0-9]*)?'
    model: main.daos.User
    controller: main.controllers.UserController

# =========================
# Challenges Microservice
# =========================

  - regex: '^/user(/*[a-zA-Z0-9]*)?'
    model: main.challenges.models.Challenge

# =========================
# Completion Criteria Microservice
# =========================

  - regex: '^/user(/*[a-zA-Z0-9]*)?'
    model: main.completionCriterias.models.CompletionCriteria

# =========================
# Rewards Microservice
# =========================

  - regex: '^/user(/*[a-zA-Z0-9]*)?'
    model: main.rewards.models.Reward

# =========================
# Token Microservice
# =========================

  - regex: '^/user(/*[a-zA-Z0-9]*)?'
    model: main.tokens.models.Token

# =========================
# Transactions Microservice
# =========================

  - regex: '^/user(/*[a-zA-Z0-9]*)?'
    model: main.transactions.models.Transaction

# =========================
# User Account Microservice
# =========================

  - regex: '^/user(/*[a-zA-Z0-9]*)?'
    model: main.userAccounts.models.UserAccount
